### PR TITLE
fix(dependency-injection): ignore ...rest TypeScript metadata

### LINKED ISSUE #171: Bug: Cannot use spread with the injector (Injection With Inheritance in Aurelia)
**I'm submitting a bug report**

* **Library Version:**
1.4.1
(Webpack build uses `native-modules` dist)

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v8.11.1

* **Yarn Version:**
1.5.1

* **Webpack Version**
Webpack 4.16.5

* **Browser:**
Chrome

* **Language:**
TypeScript 3.0.1

**Current behavior:**
Using the spread operator doesn't work as per the blog post here with TypeScript, for some reason it seems to generate an additional empty object parameter?

I also have to make each property optional on the base class, which isn't ideal but workable.

https://ilikekillnerds.com/2016/11/injection-inheritance-aurelia/

```ts
import { autoinject, containerless } from 'aurelia-framework';
import { I18N } from 'aurelia-i18n';

@autoinject
@containerless
export abstract class BaseDialog {
	constructor(
		protected readonly controller?: DialogController,
		protected readonly element?: Element,
	) {

	}
}

@autoinject
export class NotesDialog extends BaseDialog {
	constructor(
		protected readonly i18n: I18N,
		protected readonly dialogUtils: DialogUtils,
		...rest
	) {
		super(...rest);
		// rest[0] = {}; <- Why is this empty object here?
		// rest[1] = DialogController
		// rest[2] = Element;
		console.warn('NotesDialog', rest);
	}
}
```

Additionally, if I console.log the "NotesDialog.inject" static property at run-time, I get:
```
0: ƒ I18N(ea, signaler)
1: ƒ DialogUtils(dialogService, i18n)
2: ƒ Object()
```

**Expected/desired behavior:**
I'd expect to be able to use the "...rest" pattern so I don't need to update each subclass if I update the dependencies on the base class.

### PR DESCRIPTION
**Pull request by silbinarywolf**
This isn't as elegant as I would like... but I'm open to suggestions if there's a better place for this fix.

Fixes #171

### CODE REVIEW

**Comment by silbinarywolf** [comment]
@fkleuver or @EisenbergEffect, If you could review this when you've got the chance, that'd be fantastic :)

**Comment by EisenbergEffect** [comment]
Interesting. It seems ok. I believe @fkleuver has more experience dealing with this than me though. So, I'll defer the final decision to him.

**Comment by fkleuver** [comment]
Overall you added a good test for the happy path, but it would be nice to see a few variations and potential edge cases addressed as well (even if they can be inferred with common sense and seem redundant).

Such cases would be:
```ts
class Dep$1 {}
class Dep$2 {}
class Dep$3 {}
class Dep$4 {}
class Dep$5 {}

// happy path
class ParentOneDep {
  constructor(dep1: Dep$1) {
    this.dep1 = dep1;
  }
}
// double check with two deps
class ParentTwoDeps {
  constructor(dep1: Dep$1, dep2: Dep$2) {
    this.dep1 = dep1;
    this.dep2 = dep2;
  }
}

class ChildZeroDeps$1 extends ParentOneDep {}
class ChildZeroDeps$2 extends ParentTwoDeps {}

class ChildOneDep$1 extends ParentOneDep {
  constructor(dep3: Dep$3, ...rest) {
    super(...rest);
    this.dep3 = dep3;
  }
}
class ChildOneDep$2 extends ParentTwoDeps {
  constructor(dep3: Dep$3, ...rest) {
    super(...rest);
    this.dep3 = dep3;
  }
}

class ChildTwoDeps$1 extends ParentOneDep {
  constructor(dep3: Dep$3, dep4: Dep$4, ...rest) {
    super(...rest);
    this.dep3 = dep3;
    this.dep4 = dep4;
  }
}
class ChildTwoDeps$2 extends ParentTwoDeps {
  constructor(dep3: Dep$3, dep4: Dep$4, ...rest) {
    super(...rest);
    this.dep3 = dep3;
    this.dep4 = dep4;
  }
}

// check dep1
class GrandChildZeroDeps$01 extends ChildZeroDeps$1 {}

// check dep1, dep2
class GrandChildZeroDeps$02 extends ChildZeroDeps$2 {}

// check dep1, dep3
class GrandChildZeroDeps$11 extends ChildOneDep$1 {}

// check dep1, dep3, dep4
class GrandChildZeroDeps$12 extends ChildOneDep$2 {}

// check dep1, dep2, dep3
class GrandChildZeroDeps$21 extends ChildTwoDeps$1 {}

// check dep1, dep2, dep3, dep4
class GrandChildZeroDeps$22 extends ChildTwoDeps$2 {}

// check dep1, dep5
class GrandChildOneDep$01 extends ChildZeroDeps$1 {
  constructor(dep5: Dep$5, ...rest) {
    super(...rest);
    this.dep5 = dep5;
  }
}

// check dep1, dep2, dep5
class GrandChildOneDep$02 extends ChildZeroDeps$2 {
  constructor(dep5: Dep$5, ...rest) {
    super(...rest);
    this.dep5 = dep5;
  }
}

// check dep1, dep3, dep5
class GrandChildOneDep$11 extends ChildOneDep$1 {
  constructor(dep5: Dep$5, ...rest) {
    super(...rest);
    this.dep5 = dep5;
  }
}

// check dep1, dep3, dep4, dep5
class GrandChildOneDep$12 extends ChildOneDep$2 {
  constructor(dep5: Dep$5, ...rest) {
    super(...rest);
    this.dep5 = dep5;
  }
}

// check dep1, dep2, dep3, dep5
class GrandChildOneDep$21 extends ChildTwoDeps$1 {
  constructor(dep5: Dep$5, ...rest) {
    super(...rest);
    this.dep5 = dep5;
  }
}

// check dep1, dep2, dep3, dep4, dep5
class GrandChildOneDep$22 extends ChildTwoDeps$2 {
  constructor(dep5: Dep$5, ...rest) {
    super(...rest);
    this.dep5 = dep5;
  }
}
```

Now this may seem like a lot and tedious, so it's entirely up to you whether you're up for it. I'll do it a bit later otherwise.

Reason being, I would like to see the reliability (lack of regressions) of vCurrent improving over time with addition of more tests, not potentially degrading with only the addition of more features (which unfortunately has been happening too often with feature PRs). Not saying that's the case now - this PR is neutral in that respect.

Let me know if you're willing to do that with a couple of looped tests or some such. If not (maybe you're too busy now), that's completely fine of course. Thanks!

**Comment by silbinarywolf** [comment]
I'll see if I can add those additional test cases in within the next 3 business days :)

**Comment by fkleuver** [comment]
Excellent, thank you! This instills some confidence :)

LGTM @EisenbergEffect let's get this in

**Comment by EisenbergEffect** [comment]
Thanks @silbinarywolf for contributing this work back to the core. I'm sure many TS devs will be happy about this fix :)

**Pull request merged**
