### PR TITLE
Parent resolver

### LINKED ISSUE #8: Allow injection of parent routers without creating new Child Router
Currently, it is possible to get the parent of a router in a child viewmodel by creating a child router and referencing its parent. There is no way to directly inject the parent router.

Use case for this includes child viewmodels that may wish to call `router.navigate`, `router.navigateBack`, or other router methods on the router that owns it.

### PR DESCRIPTION
**Pull request by tyrsius**
Add Parent resolved to fix #8

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Ok. One final nitpick. Would you be able to squash all these commits into a single commit? ;)

**Comment by tyrsius** [comment]
I'll try, I've never done that before

**Comment by tyrsius** [comment]
@EisenbergEffect I hope I did that right, I've never squashed old commits on a public repo, and I had to fiddle with it quite a bit.

**Comment by EisenbergEffect** [comment]
It looks good! I'll get it in a bit later today.

**Pull request merged**
