### PR TITLE
feat(resolvers): add NewInstance resolver

### PR DESCRIPTION
**Pull request by jdanyow**

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Release coming in just a minute...

**Comment by AdamWillden** [comment]
@jdanyow @EisenbergEffect is NewInstance available in typescript? I tried referencing it but had no joy:

image

I'm new to typescript so don't know what to look for in this repo to be sure.

**Comment by EisenbergEffect** [comment]
That's odd. I just checked the source and the d.ts file and confirmed it's in there. Do you have the release candidate?

**Comment by AdamWillden** [comment]
@EisenbergEffect I just found the relevant code too. I copied the stuff from the blog about updating typings and have just clicked that obviously that's obviously already out of date.

Please excuse my ignorance - catching up on typescript still!

**Comment by EisenbergEffect** [comment]
No problem. Glad it's working :)

**Comment by AdamWillden** [comment]
Well as soon as I figure out how to update the typings it will be!

**Pull request merged**
