### PR TITLE
Remove internal module from d.ts file

### PR DESCRIPTION
**Pull request by DrSammyD**
I updated the dts-bundle-generator to dts-generator, which has options to exclude particular d.ts files.

### CODE REVIEW

**Comment by bigopon** [comment]
@DrSammyD It seems all the issues could simply be solved with `stripInternal: true` on? If my assessment is correct, then what else did you find that required you to fix other parts?

**Comment by DrSammyD** [comment]
> @DrSammyD It seems all the issues could simply be solved with `stripInternal: true` on? If my assessment is correct, then what else did you find that required you to fix other parts?

I initially tried [that](https://github.com/aurelia/dependency-injection/pull/181/files#diff-17d19956339a21e53394cda05f5a6cc3R20), but I think that only works for properties not modules.

**Comment by EisenbergEffect** [comment]
Good to merge @bigopon @DrSammyD ???

**Comment by DrSammyD** [comment]
Unless @bigopon knows a way to strip internal for declared modules, I'm good.

**Comment by bigopon** [comment]
Ill have a test one more time to9. If needed, ill commit based on @DrSammyD changes

**Comment by DrSammyD** [comment]
This PR over at e2e tests should make main circleci pass https://github.com/aurelia/e2e-tests/pull/3#issue-296494897

**Comment by bigopon** [comment]
@DrSammyD I resolved the issue here https://github.com/bigopon/aurelia-dependency-injection/commit/363635d09146a8637a77c853bc6165cccc6f7137#diff-ab4d9046ca9b8b80b3d5a561a7846b1eR2

Mostly it's just import the declaration into the main to propagate the extensions to other modules, instead of using <references/>

And please use dts-bundle-generator, it's used across all other plugins/repos of Aurelia. We would want to unify this.

**Comment by DrSammyD** [comment]
Pop Pop!
image
image

**Comment by EisenbergEffect** [comment]
One final look from @bigopon and we can get this in and released.

**Comment by bigopon** [comment]
🎉

**Comment by bigopon** [comment]
Lgtm 😀

**Pull request merged**
